// This file is auto-generated by generate-version.js during build. Do not edit.
export const APP_VERSION = '2.5.0';
export const BUILD_NUMBER = '20260917.de1750c';
export const BUILD_DATE = '17/09/2026';
export const FULL_VERSION = `v${APP_VERSION} (Build ${BUILD_NUMBER})`;
