// This file is auto-generated by generate-version.js during build. Do not edit.
export const APP_VERSION = '2.5.0';
export const BUILD_NUMBER = '20260912.fe5fbed';
export const BUILD_DATE = '12/09/2026';
export const FULL_VERSION = `v${APP_VERSION} (Build ${BUILD_NUMBER})`;
