// This file is auto-generated by generate-version.js during build. Do not edit.
export const APP_VERSION = '2.5.0';
export const BUILD_NUMBER = '20260913.2e8c4ec';
export const BUILD_DATE = '13/09/2026';
export const FULL_VERSION = `v${APP_VERSION} (Build ${BUILD_NUMBER})`;
